<?php

namespace ContainerYgyMucS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MZxKj1lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mZxKj1l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mZxKj1l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'presenter' => ['privates', 'App\\Service\\TwitterPresenter', 'getTwitterPresenterService', true],
        ], [
            'presenter' => '?',
        ]);
    }
}
