<?php

namespace ContainerYgyMucS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwitterPresenterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TwitterPresenter' shared autowired service.
     *
     * @return \App\Service\TwitterPresenter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Model/TwitterPresenterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/TwitterPresenter.php';

        return $container->privates['App\\Service\\TwitterPresenter'] = new \App\Service\TwitterPresenter();
    }
}
