<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYgyMucS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYgyMucS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYgyMucS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYgyMucS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYgyMucS\App_KernelDevDebugContainer([
    'container.build_hash' => 'YgyMucS',
    'container.build_id' => 'f7ec7d55',
    'container.build_time' => 1630897629,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYgyMucS');
